/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClaudeCodeMcpRouteImport } from './routes/claude-code/mcp'
import { Route as ToolVendorsRouteImport } from './routes/$tool/vendors'
import { Route as ToolToolsRouteImport } from './routes/$tool/tools'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaudeCodeMcpRoute = ClaudeCodeMcpRouteImport.update({
  id: '/claude-code/mcp',
  path: '/claude-code/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolVendorsRoute = ToolVendorsRouteImport.update({
  id: '/$tool/vendors',
  path: '/$tool/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolToolsRoute = ToolToolsRouteImport.update({
  id: '/$tool/tools',
  path: '/$tool/tools',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$tool/tools': typeof ToolToolsRoute
  '/$tool/vendors': typeof ToolVendorsRoute
  '/claude-code/mcp': typeof ClaudeCodeMcpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$tool/tools': typeof ToolToolsRoute
  '/$tool/vendors': typeof ToolVendorsRoute
  '/claude-code/mcp': typeof ClaudeCodeMcpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$tool/tools': typeof ToolToolsRoute
  '/$tool/vendors': typeof ToolVendorsRoute
  '/claude-code/mcp': typeof ClaudeCodeMcpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$tool/tools' | '/$tool/vendors' | '/claude-code/mcp'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$tool/tools' | '/$tool/vendors' | '/claude-code/mcp'
  id: '__root__' | '/' | '/$tool/tools' | '/$tool/vendors' | '/claude-code/mcp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolToolsRoute: typeof ToolToolsRoute
  ToolVendorsRoute: typeof ToolVendorsRoute
  ClaudeCodeMcpRoute: typeof ClaudeCodeMcpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claude-code/mcp': {
      id: '/claude-code/mcp'
      path: '/claude-code/mcp'
      fullPath: '/claude-code/mcp'
      preLoaderRoute: typeof ClaudeCodeMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tool/vendors': {
      id: '/$tool/vendors'
      path: '/$tool/vendors'
      fullPath: '/$tool/vendors'
      preLoaderRoute: typeof ToolVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tool/tools': {
      id: '/$tool/tools'
      path: '/$tool/tools'
      fullPath: '/$tool/tools'
      preLoaderRoute: typeof ToolToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolToolsRoute: ToolToolsRoute,
  ToolVendorsRoute: ToolVendorsRoute,
  ClaudeCodeMcpRoute: ClaudeCodeMcpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
